# Generated by Django 5.2.7 on 2025-10-02 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("communications", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="galleries/covers/"
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_galleries",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="galleries",
                        to="communications.event",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galleries",
                        to="tenants.organization",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galleries",
                        to="tenants.school",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Galleries",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="galleries/images/")),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cms.gallery",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="tenants.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_images",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="NavigationMenu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
                ("href", models.CharField(blank=True, max_length=255)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "menu_type",
                    models.CharField(
                        choices=[
                            ("page", "Page"),
                            ("section", "Section"),
                            ("dropdown", "Dropdown"),
                            ("external", "External Link"),
                        ],
                        default="page",
                        max_length=20,
                    ),
                ),
                ("is_external", models.BooleanField(default=False)),
                ("external_url", models.URLField(blank=True)),
                ("open_in_new_tab", models.BooleanField(default=False)),
                ("show_in_navigation", models.BooleanField(default=True)),
                ("show_in_footer", models.BooleanField(default=False)),
                ("show_in_landing_page", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navigation_menus",
                        to="tenants.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="cms.navigationmenu",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="navigation_menus",
                        to="tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="pages/heroes/"),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="tenants.organization",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Section"),
                            ("about", "About"),
                            ("features", "Features"),
                            ("gallery", "Gallery"),
                            ("news", "News"),
                            ("events", "Events"),
                            ("contact", "Contact"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                ("content", models.JSONField(default=dict)),
                ("display_order", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("background_color", models.CharField(blank=True, max_length=7)),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="sections/backgrounds/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="tenants.organization",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="cms.page",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="documents/")),
                ("file_size", models.BigIntegerField()),
                ("file_type", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("policy", "Policy"),
                            ("form", "Form"),
                            ("syllabus", "Syllabus"),
                            ("report", "Report"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("download_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="tenants.organization",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="tenants.school",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "school", "is_public"],
                        name="cms_documen_organiz_b14266_idx",
                    ),
                    models.Index(
                        fields=["category"], name="cms_documen_categor_e46d14_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="gallery",
            index=models.Index(
                fields=["organization", "school", "is_published"],
                name="cms_gallery_organiz_0291cd_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gallery",
            unique_together={("organization", "school", "slug")},
        ),
        migrations.AddIndex(
            model_name="galleryimage",
            index=models.Index(
                fields=["organization", "gallery", "display_order"],
                name="cms_gallery_organiz_32714e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="navigationmenu",
            index=models.Index(
                fields=["organization", "school", "is_active"],
                name="cms_navigat_organiz_c5b36e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="navigationmenu",
            index=models.Index(
                fields=["parent", "display_order"],
                name="cms_navigat_parent__b50f11_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="navigationmenu",
            unique_together={("organization", "school", "slug", "parent")},
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(
                fields=["organization", "school", "is_published"],
                name="cms_page_organiz_501741_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="page",
            index=models.Index(fields=["slug"], name="cms_page_slug_f9a361_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="page",
            unique_together={("organization", "school", "slug")},
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["organization", "school", "is_visible"],
                name="cms_section_organiz_67802c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["page", "display_order"], name="cms_section_page_id_18e5a4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("organization", "school", "page", "slug")},
        ),
    ]
