# Generated by Django 5.2.7 on 2026-03-11 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="galleries/covers/"
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_galleries",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="galleries",
                        to="communications.event",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Galleries",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="galleries/images/")),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cms.gallery",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_images",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Marquee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("link", models.CharField(blank=True, max_length=255)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="cms_marquee_is_acti_ccb6f6_idx"
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="cms_marquee_start_d_e11629_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NavigationMenu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("href", models.CharField(blank=True, max_length=255)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "menu_type",
                    models.CharField(
                        choices=[
                            ("page", "Page"),
                            ("section", "Section"),
                            ("dropdown", "Dropdown"),
                            ("external", "External Link"),
                        ],
                        default="page",
                        max_length=20,
                    ),
                ),
                ("is_external", models.BooleanField(default=False)),
                ("external_url", models.URLField(blank=True)),
                ("open_in_new_tab", models.BooleanField(default=False)),
                ("show_in_navigation", models.BooleanField(default=True)),
                ("show_in_footer", models.BooleanField(default=False)),
                ("show_in_landing_page", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="cms.navigationmenu",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.CharField(db_index=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="pages/heroes/"),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
                "indexes": [
                    models.Index(
                        fields=["is_published"], name="cms_page_is_publ_00a054_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="documents/")),
                ("file_size", models.BigIntegerField()),
                ("file_type", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("policy", "Policy"),
                            ("form", "Form"),
                            ("syllabus", "Syllabus"),
                            ("report", "Report"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("download_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Link document to a specific page",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Section"),
                            ("about", "About"),
                            ("features", "Features"),
                            ("gallery", "Gallery"),
                            ("news", "News"),
                            ("events", "Events"),
                            ("contact", "Contact"),
                            ("principal", "Principal Message"),
                            ("courses", "Courses"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                ("content", models.JSONField(default=dict)),
                ("display_order", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("background_color", models.CharField(blank=True, max_length=7)),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="sections/backgrounds/"
                    ),
                ),
                ("show_in_landing_page", models.BooleanField(default=False)),
                (
                    "landing_page_order",
                    models.IntegerField(
                        default=0, help_text="Order of section on landing page"
                    ),
                ),
                (
                    "landing_page_width",
                    models.CharField(
                        choices=[
                            ("full", "Full Width"),
                            ("three-quarters", "Three Quarters (3/4)"),
                            ("two-thirds", "Two Thirds (2/3)"),
                            ("half", "Half (1/2)"),
                            ("third", "One Third (1/3)"),
                            ("quarter", "Quarter (1/4)"),
                        ],
                        default="full",
                        help_text="Width of section on landing page. Partial-width sections appear side by side.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="cms.page",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="sliders/")),
                ("cta_text", models.CharField(blank=True, max_length=100)),
                ("cta_link", models.CharField(blank=True, max_length=255)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="cms_slider_is_acti_e3faa0_idx"
                    ),
                    models.Index(
                        fields=["display_order"], name="cms_slider_display_4b5aaf_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="gallery",
            index=models.Index(
                fields=["is_published"], name="cms_gallery_is_publ_882ecc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="galleryimage",
            index=models.Index(
                fields=["gallery", "display_order"],
                name="cms_gallery_gallery_7128a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="navigationmenu",
            index=models.Index(
                fields=["is_active"], name="cms_navigat_is_acti_4f227a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="navigationmenu",
            index=models.Index(
                fields=["parent", "display_order"],
                name="cms_navigat_parent__b50f11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_public"], name="cms_documen_is_publ_83c4b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["category"], name="cms_documen_categor_e46d14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["page"], name="cms_documen_page_id_39f40a_idx"),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["is_visible"], name="cms_section_is_visi_aba201_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["page", "display_order"], name="cms_section_page_id_18e5a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["show_in_landing_page", "landing_page_order"],
                name="cms_section_show_in_38df74_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("page", "slug")},
        ),
    ]
