# Generated by Django 5.2.7 on 2026-03-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
        ("tenants", "0002_school_config_school_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="landing_page_order",
            field=models.IntegerField(
                default=0, help_text="Order of section on landing page"
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="show_in_landing_page",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="section",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("hero", "Hero Section"),
                    ("about", "About"),
                    ("features", "Features"),
                    ("gallery", "Gallery"),
                    ("news", "News"),
                    ("events", "Events"),
                    ("contact", "Contact"),
                    ("principal", "Principal Message"),
                    ("courses", "Courses"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=[
                    "organization",
                    "school",
                    "show_in_landing_page",
                    "landing_page_order",
                ],
                name="cms_section_organiz_aaa061_idx",
            ),
        ),
    ]
