# Generated by Django 5.2.7 on 2026-03-11 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("cms", "0002_add_landing_page_fields_to_section"),
        ("tenants", "0002_school_config_school_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="page",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Link document to a specific page",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="cms.page",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["page"], name="cms_documen_page_id_39f40a_idx"),
        ),
    ]
