# Generated by Django 5.2.7 on 2026-03-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_document_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
