# Generated by Django 5.2.7 on 2026-03-11 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("cms", "0004_change_page_slug_to_charfield"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="document",
            name="cms_documen_organiz_b14266_idx",
        ),
        migrations.RemoveField(
            model_name="document",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="document",
            name="school",
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_documents",
                to="accounts.userprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_public"], name="cms_documen_is_publ_83c4b6_idx"
            ),
        ),
    ]
