# Generated by Django 5.2.7 on 2026-03-11 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_remove_document_multitenancy"),
        ("tenants", "0002_school_config_school_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marquee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("link", models.CharField(blank=True, max_length=255)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marquees",
                        to="tenants.organization",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marquees",
                        to="tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "school", "is_active"],
                        name="cms_marquee_organiz_fe7add_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="cms_marquee_start_d_e11629_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="sliders/")),
                ("cta_text", models.CharField(blank=True, max_length=100)),
                ("cta_link", models.CharField(blank=True, max_length=255)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sliders",
                        to="tenants.organization",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sliders",
                        to="tenants.school",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "school", "is_active"],
                        name="cms_slider_organiz_25abb7_idx",
                    ),
                    models.Index(
                        fields=["display_order"], name="cms_slider_display_4b5aaf_idx"
                    ),
                ],
            },
        ),
    ]
