# Generated by Django 6.0.3 on 2026-03-21 08:39

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0008_migrate_class_to_section"),
        ("accounts", "0002_userprofile_must_change_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code for the category (e.g., TUI, TRA, LIB)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="If true, this fee is required for all students",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fee Category",
                "verbose_name_plural": "Fee Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FeeDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for this discount",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage or fixed amount",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum discount cap (for percentage discounts)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "criteria",
                    models.CharField(
                        choices=[
                            ("sibling", "Sibling Discount"),
                            ("merit", "Merit Scholarship"),
                            ("staff_child", "Staff Child"),
                            ("financial_aid", "Financial Aid"),
                            ("sports_quota", "Sports Quota"),
                            ("early_bird", "Early Bird Payment"),
                            ("custom", "Custom/Other"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "is_combinable",
                    models.BooleanField(
                        default=False,
                        help_text="Can this discount be combined with others?",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        help_text="If null, applies to all academic years",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_discounts",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "applicable_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to apply to all categories",
                        related_name="discounts",
                        to="fees.feecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Discount",
                "verbose_name_plural": "Fee Discounts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name (e.g., 'Class 10 Tuition Fee 2025-26')",
                        max_length=200,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("one_time", "One Time"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("half_yearly", "Half Yearly"),
                            ("yearly", "Yearly"),
                        ],
                        default="yearly",
                        max_length=20,
                    ),
                ),
                (
                    "due_day_of_month",
                    models.IntegerField(
                        default=10,
                        help_text="Day of month when fee is due (1-28)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
                (
                    "late_fee_type",
                    models.CharField(
                        choices=[
                            ("none", "No Late Fee"),
                            ("fixed", "Fixed Amount"),
                            ("percentage", "Percentage of Fee"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "late_fee_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount or percentage for late fee",
                        max_digits=10,
                    ),
                ),
                (
                    "grace_period_days",
                    models.IntegerField(
                        default=0,
                        help_text="Days after due date before late fee applies",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_refundable", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structures",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structures",
                        to="fees.feecategory",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        help_text="If null, applies to all grades",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structures",
                        to="academics.grade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Structure",
                "verbose_name_plural": "Fee Structures",
                "ordering": ["academic_year", "grade", "category__display_order"],
                "unique_together": {
                    ("academic_year", "grade", "category", "frequency")
                },
            },
        ),
        migrations.CreateModel(
            name="StudentFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(help_text="Start date of the fee period"),
                ),
                (
                    "period_end",
                    models.DateField(help_text="End date of the fee period"),
                ),
                ("due_date", models.DateField()),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original fee amount from structure",
                        max_digits=10,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "late_fee_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base amount - discount + late fee",
                        max_digits=10,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partially Paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("waived", "Waived"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "waiver_reason",
                    models.TextField(blank=True, help_text="Reason if fee was waived"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discounts_applied",
                    models.ManyToManyField(
                        blank=True, related_name="student_fees", to="fees.feediscount"
                    ),
                ),
                (
                    "fee_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_fees",
                        to="fees.feestructure",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="academics.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Fee",
                "verbose_name_plural": "Student Fees",
                "ordering": ["-due_date", "student"],
                "unique_together": {
                    ("student", "fee_structure", "period_start", "period_end")
                },
            },
        ),
        migrations.CreateModel(
            name="FeeReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming Due Date"),
                            ("due", "Due Date Reminder"),
                            ("overdue", "Overdue Notice"),
                            ("final", "Final Notice"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("app", "App Notification"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_to",
                    models.CharField(
                        help_text="Email/Phone number sent to", max_length=200
                    ),
                ),
                ("is_delivered", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("message_content", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "student_fee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="fees.studentfee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Reminder",
                "verbose_name_plural": "Fee Reminders",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="FeePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("bank_transfer", "Bank Transfer"),
                            ("upi", "UPI"),
                            ("card", "Credit/Debit Card"),
                            ("online", "Online Payment"),
                            ("dd", "Demand Draft"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        help_text="Auto-generated receipt number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="External transaction reference",
                        max_length=100,
                    ),
                ),
                ("cheque_number", models.CharField(blank=True, max_length=50)),
                ("cheque_date", models.DateField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "refund_reason",
                    models.TextField(
                        blank=True, help_text="Reason if payment was refunded"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payments",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_payments",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "student_fee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="fees.studentfee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Payment",
                "verbose_name_plural": "Fee Payments",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
    ]
