# Generated by Django 5.2.7 on 2025-10-02 09:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "domain",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("settings", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="tenants_org_slug_3f63d7_idx"),
                    models.Index(
                        fields=["domain"], name="tenants_org_domain_252ecf_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="tenants_org_is_acti_f49d84_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "billing_period",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("max_students", models.IntegerField(blank=True, null=True)),
                ("max_staff", models.IntegerField(blank=True, null=True)),
                ("max_storage_gb", models.IntegerField(blank=True, null=True)),
                ("features", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "price"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="tenants_sub_is_acti_4bc4df_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("trial_start_date", models.DateField(blank=True, null=True)),
                ("trial_end_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("auto_renew", models.BooleanField(default=True)),
                ("current_students", models.IntegerField(default=0)),
                ("current_staff", models.IntegerField(default=0)),
                (
                    "current_storage_gb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="tenants.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="tenants.subscriptionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("model_name", models.CharField(max_length=100)),
                ("object_id", models.UUIDField()),
                ("changes", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"],
                        name="tenants_aud_organiz_591341_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="tenants_aud_user_id_e62ef0_idx",
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="tenants_aud_model_n_599237_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(blank=True, max_length=100)),
                ("tagline", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "established_year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1800),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("website", models.URLField(blank=True)),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="schools/logos/"
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="schools/banners/"
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active"],
                        name="tenants_sch_organiz_76c372_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="tenants.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-invoice_date"],
                "indexes": [
                    models.Index(
                        fields=["subscription", "status"],
                        name="tenants_inv_subscri_a82837_idx",
                    ),
                    models.Index(
                        fields=["invoice_date"], name="tenants_inv_invoice_710c3a_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["organization", "status"], name="tenants_sub_organiz_d5a2e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["end_date"], name="tenants_sub_end_dat_820fde_idx"
            ),
        ),
    ]
