# Generated by Django 5.2.7 on 2025-11-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="config",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="school",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["slug"], name="tenants_sch_slug_07a116_idx"),
        ),
    ]
