# Generated by Django 5.2.7 on 2026-03-13 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "is_sequential",
                    models.BooleanField(
                        default=True,
                        help_text="If True, steps must be completed in order",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="workflows_a_is_acti_c240a5_idx"
                    ),
                    models.Index(fields=["slug"], name="workflows_a_slug_7c3866_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ApprovalStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("step_order", models.IntegerField(default=1)),
                (
                    "approver_type",
                    models.CharField(
                        choices=[
                            ("role", "Role-based"),
                            ("specific_user", "Specific User"),
                            ("department", "Department Head"),
                            ("class_teacher", "Class Teacher"),
                            ("parent", "Parent/Guardian"),
                        ],
                        default="role",
                        max_length=50,
                    ),
                ),
                (
                    "approver_role",
                    models.CharField(
                        blank=True,
                        help_text="Role required for approval (if approver_type is 'role')",
                        max_length=50,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Department name (if approver_type is 'department')",
                        max_length=100,
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(
                        default=False, help_text="If True, this step can be skipped"
                    ),
                ),
                (
                    "can_reject",
                    models.BooleanField(
                        default=True,
                        help_text="If True, approver can reject the request",
                    ),
                ),
                (
                    "requires_comment",
                    models.BooleanField(
                        default=False,
                        help_text="If True, approver must provide a comment",
                    ),
                ),
                (
                    "auto_approve_after_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Auto-approve after this many days if not actioned",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific user (if approver_type is 'specific_user')",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_approval_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="workflows.approvalworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["workflow", "step_order"],
            },
        ),
        migrations.CreateModel(
            name="ClearanceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("department", models.CharField(max_length=100)),
                (
                    "clearance_role",
                    models.CharField(
                        help_text="Role that can provide this clearance", max_length=50
                    ),
                ),
                ("clearance_order", models.IntegerField(default=1)),
                (
                    "check_description",
                    models.TextField(
                        blank=True,
                        help_text="What this clearance verifies (e.g., 'No pending library books')",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["clearance_order"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="workflows_c_is_acti_f84d7a_idx"
                    ),
                    models.Index(fields=["slug"], name="workflows_c_slug_15ed0a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_number", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "form_data",
                    models.JSONField(
                        default=dict,
                        help_text="Dynamic form data based on request type schema",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("pending_approval", "Pending Approval"),
                            ("pending_clearance", "Pending Clearance"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "is_bypassed",
                    models.BooleanField(
                        default=False,
                        help_text="True if approval was bypassed by authorized user",
                    ),
                ),
                ("bypassed_at", models.DateTimeField(blank=True, null=True)),
                ("bypass_reason", models.TextField(blank=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not Required"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="not_required",
                        max_length=20,
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_transaction_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("attachments_count", models.IntegerField(default=0)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bypassed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bypassed_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_requests",
                        to="workflows.approvalstep",
                    ),
                ),
                (
                    "on_behalf_of_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="academics.student",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("skipped", "Skipped"),
                            ("bypassed", "Bypassed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("actioned_at", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_records",
                        to="workflows.approvalstep",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="given_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="workflows.request",
                    ),
                ),
            ],
            options={
                "ordering": ["approval_step__step_order"],
            },
        ),
        migrations.CreateModel(
            name="RequestAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="requests/attachments/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=100)),
                ("file_size", models.IntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="workflows.request",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestClearance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("cleared", "Cleared"),
                            ("not_cleared", "Not Cleared"),
                            ("bypassed", "Bypassed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verification_notes", models.TextField(blank=True)),
                (
                    "pending_dues",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount of pending dues (if any)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "pending_items",
                    models.TextField(
                        blank=True,
                        help_text="Description of pending items (e.g., library books)",
                    ),
                ),
                ("actioned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clearance_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clearance_records",
                        to="workflows.clearancetype",
                    ),
                ),
                (
                    "cleared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="given_clearances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clearances",
                        to="workflows.request",
                    ),
                ),
            ],
            options={
                "ordering": ["clearance_type__clearance_order"],
            },
        ),
        migrations.CreateModel(
            name="RequestHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("submitted", "Submitted"),
                            ("status_changed", "Status Changed"),
                            ("approval_given", "Approval Given"),
                            ("approval_rejected", "Approval Rejected"),
                            ("clearance_given", "Clearance Given"),
                            ("clearance_denied", "Clearance Denied"),
                            ("bypassed", "Bypassed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("comment_added", "Comment Added"),
                            ("attachment_added", "Attachment Added"),
                        ],
                        max_length=50,
                    ),
                ),
                ("previous_status", models.CharField(blank=True, max_length=30)),
                ("new_status", models.CharField(blank=True, max_length=30)),
                ("details", models.JSONField(default=dict)),
                ("comments", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="workflows.request",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Request histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("administrative", "Administrative"),
                            ("financial", "Financial"),
                            ("transport", "Transport"),
                            ("communication", "Communication"),
                        ],
                        default="administrative",
                        max_length=50,
                    ),
                ),
                (
                    "requires_clearance",
                    models.BooleanField(
                        default=False,
                        help_text="If True, request requires multi-department clearance (e.g., TC)",
                    ),
                ),
                ("requires_payment", models.BooleanField(default=False)),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "form_schema",
                    models.JSONField(
                        default=dict,
                        help_text="JSON schema for the request form fields",
                    ),
                ),
                (
                    "allowed_roles",
                    models.JSONField(
                        default=list,
                        help_text="List of roles that can submit this request type",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval_workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_types",
                        to="workflows.approvalworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="request",
            name="request_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="workflows.requesttype",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalstep",
            index=models.Index(
                fields=["workflow", "step_order"], name="workflows_a_workflo_f2a48c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="approvalstep",
            unique_together={("workflow", "step_order")},
        ),
        migrations.AddIndex(
            model_name="requestapproval",
            index=models.Index(
                fields=["request", "status"], name="workflows_r_request_1c112e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requestapproval",
            index=models.Index(
                fields=["approved_by", "status"], name="workflows_r_approve_bc5f05_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="requestapproval",
            unique_together={("request", "approval_step")},
        ),
        migrations.AddIndex(
            model_name="requestattachment",
            index=models.Index(
                fields=["request"], name="workflows_r_request_2d8787_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requestclearance",
            index=models.Index(
                fields=["request", "status"], name="workflows_r_request_82918d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requestclearance",
            index=models.Index(
                fields=["cleared_by"], name="workflows_r_cleared_e72714_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="requestclearance",
            unique_together={("request", "clearance_type")},
        ),
        migrations.AddIndex(
            model_name="requesthistory",
            index=models.Index(
                fields=["request", "-created_at"], name="workflows_r_request_eaed2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requesthistory",
            index=models.Index(
                fields=["action_by"], name="workflows_r_action__7b178b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requesttype",
            index=models.Index(
                fields=["is_active", "category"], name="workflows_r_is_acti_ef986a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requesttype",
            index=models.Index(fields=["slug"], name="workflows_r_slug_5792eb_idx"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["request_number"], name="workflows_r_request_1919d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["submitted_by", "status"], name="workflows_r_submitt_9ec5fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["request_type", "status"], name="workflows_r_request_9b77dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["status", "priority"], name="workflows_r_status_ffd82a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["on_behalf_of_student"], name="workflows_r_on_beha_f33f10_idx"
            ),
        ),
    ]
