# Generated by Django 5.2.7 on 2026-03-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_student_academic_year"),
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="request",
            name="workflows_r_on_beha_f33f10_idx",
        ),
        migrations.RemoveField(
            model_name="request",
            name="on_behalf_of_student",
        ),
        migrations.AddField(
            model_name="request",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                help_text="Student(s) this request is for (parent can select one or multiple children)",
                related_name="requests",
                to="academics.student",
            ),
        ),
    ]
