# Generated by Django 6.0.3 on 2026-03-15 12:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code e.g., CHEM, MATH, ADMIN",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "department_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("non_academic", "Non-Academic"),
                            ("administrative", "Administrative"),
                        ],
                        default="academic",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("teaching", "Teaching Staff"),
                            ("non_teaching", "Non-Teaching Staff"),
                            ("administrative", "Administrative Staff"),
                            ("management", "Management"),
                        ],
                        default="teaching",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Hierarchy level (1=lowest, higher=more senior). Used for reporting structure.",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "can_approve_leave",
                    models.BooleanField(
                        default=False,
                        help_text="Can approve leave requests of subordinates",
                    ),
                ),
                (
                    "can_manage_department",
                    models.BooleanField(
                        default=False, help_text="Can manage department settings"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-level", "name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code e.g., CL, SL, EL",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_paid", models.BooleanField(default=True)),
                (
                    "requires_document",
                    models.BooleanField(
                        default=False,
                        help_text="Requires supporting document (e.g., medical certificate)",
                    ),
                ),
                (
                    "min_days_notice",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Minimum days in advance leave must be applied",
                    ),
                ),
                (
                    "max_consecutive_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum consecutive days allowed at once",
                        null=True,
                    ),
                ),
                (
                    "applicable_gender",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("male", "Male Only"),
                            ("female", "Female Only"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color code for UI",
                        max_length=7,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_department_head",
                    models.BooleanField(
                        default=False,
                        help_text="Is this employee the head of their department?",
                    ),
                ),
                ("employee_code", models.CharField(max_length=50, unique=True)),
                ("joining_date", models.DateField()),
                ("confirmation_date", models.DateField(blank=True, null=True)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_leave", "On Leave"),
                            ("resigned", "Resigned"),
                            ("terminated", "Terminated"),
                            ("retired", "Retired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("contract", "Contract"),
                            ("probation", "Probation"),
                            ("temporary", "Temporary"),
                        ],
                        default="permanent",
                        max_length=20,
                    ),
                ),
                (
                    "work_days_per_week",
                    models.PositiveIntegerField(
                        default=6,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                ("resignation_date", models.DateField(blank=True, null=True)),
                ("last_working_date", models.DateField(blank=True, null=True)),
                ("exit_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="hr.department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="hr.designation",
                    ),
                ),
                (
                    "reports_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Direct reporting manager",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="hr.employeeprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("national", "National Holiday"),
                            ("religious", "Religious Holiday"),
                            ("school", "School Holiday"),
                            ("vacation", "Vacation"),
                        ],
                        default="national",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "is_optional",
                    models.BooleanField(
                        default=False, help_text="Optional/restricted holiday"
                    ),
                ),
                ("year", models.PositiveIntegerField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicable_departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="If empty, applies to all departments",
                        to="hr.department",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Carried forward from previous year",
                        max_digits=5,
                    ),
                ),
                (
                    "annual_quota",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Prorated annual entitlement",
                        max_digits=5,
                    ),
                ),
                (
                    "adjustment",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Manual adjustments (+/-)",
                        max_digits=5,
                    ),
                ),
                (
                    "used",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Leave days used",
                        max_digits=5,
                    ),
                ),
                (
                    "pending",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Leave days in pending requests",
                        max_digits=5,
                    ),
                ),
                (
                    "encashed",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Leave days encashed",
                        max_digits=5,
                    ),
                ),
                (
                    "lapsed",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Leave days lapsed/expired",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="hr.employeeprofile",
                    ),
                ),
                (
                    "last_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="hr.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "leave_type__name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveBalanceAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Balance"),
                            ("annual_credit", "Annual Credit"),
                            ("carryforward", "Carryforward"),
                            ("used", "Used"),
                            ("cancelled", "Cancelled"),
                            ("adjusted", "Manual Adjustment"),
                            ("encashed", "Encashed"),
                            ("lapsed", "Lapsed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "days_change",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Positive for credit, negative for debit",
                        max_digits=5,
                    ),
                ),
                ("balance_before", models.DecimalField(decimal_places=1, max_digits=5)),
                ("balance_after", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference to related object (e.g., leave request ID)",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "leave_balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="hr.leavebalance",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "start_duration_type",
                    models.CharField(
                        choices=[
                            ("full_day", "Full Day"),
                            ("first_half", "First Half"),
                            ("second_half", "Second Half"),
                        ],
                        default="full_day",
                        max_length=20,
                    ),
                ),
                (
                    "end_duration_type",
                    models.CharField(
                        choices=[
                            ("full_day", "Full Day"),
                            ("first_half", "First Half"),
                            ("second_half", "Second Half"),
                        ],
                        default="full_day",
                        max_length=20,
                    ),
                ),
                (
                    "total_days",
                    models.DecimalField(decimal_places=1, editable=False, max_digits=5),
                ),
                ("reason", models.TextField()),
                ("contact_during_leave", models.CharField(blank=True, max_length=100)),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="Supporting document if required",
                        null=True,
                        upload_to="hr/leave_documents/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("partially_approved", "Partially Approved"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_leave_approvals",
                        to="hr.employeeprofile",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="hr.employeeprofile",
                    ),
                ),
                (
                    "final_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr.employeeprofile",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="hr.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(help_text="Order in approval chain"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("acted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_approvals",
                        to="hr.employeeprofile",
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="hr.leaverequest",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "applicable_to_all",
                    models.BooleanField(
                        default=True,
                        help_text="If false, applies only to specific designations",
                    ),
                ),
                (
                    "annual_quota",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Annual leave quota in days",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "proration_method",
                    models.CharField(
                        choices=[
                            ("none", "No Proration"),
                            ("monthly", "Monthly Proration"),
                            ("quarterly", "Quarterly Proration"),
                        ],
                        default="monthly",
                        help_text="How to prorate leave for mid-year joiners",
                        max_length=20,
                    ),
                ),
                (
                    "accrual_type",
                    models.CharField(
                        choices=[
                            ("yearly", "Credited Yearly (Start of Year)"),
                            ("monthly", "Credited Monthly"),
                            ("quarterly", "Credited Quarterly"),
                        ],
                        default="yearly",
                        help_text="When leave is credited to employee balance",
                        max_length=20,
                    ),
                ),
                (
                    "carryforward_type",
                    models.CharField(
                        choices=[
                            ("none", "No Carryforward"),
                            ("full", "Full Carryforward"),
                            ("partial", "Partial Carryforward"),
                            ("encashment", "Encashment Only"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "max_carryforward_days",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Maximum days that can be carried forward",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "carryforward_expiry_months",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Months after which carried forward leave expires",
                        null=True,
                    ),
                ),
                ("allow_encashment", models.BooleanField(default=False)),
                (
                    "min_balance_for_encashment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Minimum balance required before encashment",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "max_encashment_days",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicable_designations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Designations this policy applies to (if not applicable to all)",
                        related_name="leave_policies",
                        to="hr.designation",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="hr.leavetype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Leave Policies",
                "ordering": ["leave_type__name", "-effective_from"],
            },
        ),
        migrations.AddIndex(
            model_name="employeeprofile",
            index=models.Index(
                fields=["department"], name="hr_employee_departm_295a12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeprofile",
            index=models.Index(
                fields=["designation"], name="hr_employee_designa_ad57bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeprofile",
            index=models.Index(
                fields=["reports_to"], name="hr_employee_reports_c2ec6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeprofile",
            index=models.Index(
                fields=["employment_status"], name="hr_employee_employm_87fccc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="holiday",
            unique_together={("name", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="leaveapproval",
            unique_together={("leave_request", "approver")},
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["employee", "status"], name="hr_leavereq_employe_1b7929_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["start_date", "end_date"], name="hr_leavereq_start_d_9e9e54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["current_approver"], name="hr_leavereq_current_81b2c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(fields=["status"], name="hr_leavereq_status_694c52_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="leavebalance",
            unique_together={("employee", "leave_type", "year")},
        ),
    ]
