# Generated by Django 6.0.3 on 2026-03-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetype",
            name="is_applyable",
            field=models.BooleanField(
                default=True,
                help_text="If False, this leave type is calendar-only (admin sets, staff views but cannot apply)",
            ),
        ),
    ]
