# Generated by Django 6.0.3 on 2026-03-20 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_add_is_applyable_to_leavetype"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                (
                    "check_in_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Selfie photo at check-in",
                        null=True,
                        upload_to="hr/attendance/checkin/%Y/%m/",
                    ),
                ),
                (
                    "check_in_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "check_in_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("check_in_within_geofence", models.BooleanField(default=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "check_out_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Selfie photo at check-out",
                        null=True,
                        upload_to="hr/attendance/checkout/%Y/%m/",
                    ),
                ),
                (
                    "check_out_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "check_out_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("check_out_within_geofence", models.BooleanField(default=True)),
                (
                    "hours_worked",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total hours worked (auto-calculated)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("checked_in", "Checked In"),
                            ("checked_out", "Checked Out"),
                            ("absent", "Absent"),
                            ("on_leave", "On Leave"),
                            ("half_day", "Half Day"),
                        ],
                        default="checked_in",
                        max_length=20,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("synced", "Synced"),
                            ("pending", "Pending"),
                            ("error", "Error"),
                        ],
                        default="synced",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="hr.employeeprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Attendance",
                "verbose_name_plural": "Staff Attendance Records",
                "ordering": ["-date", "-check_in_time"],
                "indexes": [
                    models.Index(
                        fields=["employee", "date"],
                        name="hr_staffatt_employe_8455c7_idx",
                    ),
                    models.Index(fields=["date"], name="hr_staffatt_date_d6ae33_idx"),
                    models.Index(
                        fields=["status"], name="hr_staffatt_status_f02ca8_idx"
                    ),
                ],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
