# Generated by Django 5.2.7 on 2025-10-02 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="tenants.organization",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profiles",
                to="tenants.organization",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_profiles",
                to="accounts.role",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profiles",
                to="tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["organization", "is_active"],
                name="accounts_ro_organiz_46fa3d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("organization", "slug")},
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["organization", "school", "is_active"],
                name="accounts_us_organiz_666080_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["employee_id"], name="accounts_us_employe_f8a1cf_idx"
            ),
        ),
    ]
