# Generated by Django 5.2.7 on 2026-03-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="must_change_password",
            field=models.BooleanField(
                default=False, help_text="User must change password on next login"
            ),
        ),
    ]
