# Generated by Django 5.2.7 on 2025-10-02 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLinks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("facebook", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("additional_links", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="tenants.organization",
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="tenants.school",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Social Links",
                "indexes": [
                    models.Index(
                        fields=["organization", "school"],
                        name="config_soci_organiz_456ffd_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ThemeConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("primary_color", models.CharField(default="#1e3a8a", max_length=7)),
                ("secondary_color", models.CharField(default="#64748b", max_length=7)),
                ("accent_color", models.CharField(default="#3b82f6", max_length=7)),
                ("success_color", models.CharField(default="#10b981", max_length=7)),
                ("warning_color", models.CharField(default="#f59e0b", max_length=7)),
                (
                    "destructive_color",
                    models.CharField(default="#ef4444", max_length=7),
                ),
                ("background_color", models.CharField(default="#ffffff", max_length=7)),
                ("foreground_color", models.CharField(default="#0f172a", max_length=7)),
                ("font_family", models.CharField(default="Inter", max_length=100)),
                ("heading_font", models.CharField(blank=True, max_length=100)),
                (
                    "layout_style",
                    models.CharField(
                        choices=[
                            ("boxed", "Boxed"),
                            ("fluid", "Fluid"),
                            ("wide", "Wide"),
                        ],
                        default="fluid",
                        max_length=20,
                    ),
                ),
                ("custom_css", models.TextField(blank=True)),
                ("settings", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_configs",
                        to="tenants.organization",
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_config",
                        to="tenants.school",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "school"],
                        name="config_them_organiz_c40a48_idx",
                    )
                ],
            },
        ),
    ]
