# Generated by Django 5.2.7 on 2026-03-13 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                help_text="Current academic session for the student",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="academics.academicyear",
            ),
        ),
    ]
