# Generated by Django 5.2.7 on 2025-10-02 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("accounts", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_years",
                to="tenants.organization",
            ),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_years",
                to="tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taught_classes",
                to="accounts.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="tenants.organization",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="academics.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="class_assigned",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="academics.class",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="tenants.organization",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taught_courses",
                to="accounts.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parents",
                to="tenants.organization",
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parents",
                to="tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="current_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="academics.class",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="tenants.organization",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="studentparent",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_parents",
                to="tenants.organization",
            ),
        ),
        migrations.AddField(
            model_name="studentparent",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.parent"
            ),
        ),
        migrations.AddField(
            model_name="studentparent",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.student"
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="students",
            field=models.ManyToManyField(
                related_name="parents",
                through="academics.StudentParent",
                to="academics.student",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="tenants.organization",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="tenants.school",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="academics.subject",
            ),
        ),
        migrations.AddIndex(
            model_name="academicyear",
            index=models.Index(
                fields=["organization", "school", "is_current"],
                name="academics_a_organiz_e9de76_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academicyear",
            unique_together={("organization", "school", "name")},
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["organization", "school", "is_active"],
                name="academics_c_organiz_fd24c4_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("organization", "school", "grade", "section")},
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["organization", "school", "status"],
                name="academics_s_organiz_589e08_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["admission_number"], name="academics_s_admissi_70a43d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("organization", "school", "admission_number")},
        ),
        migrations.AddIndex(
            model_name="studentparent",
            index=models.Index(
                fields=["organization", "student"],
                name="academics_s_organiz_079382_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentparent",
            index=models.Index(
                fields=["organization", "parent"], name="academics_s_organiz_686df0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentparent",
            unique_together={("organization", "student", "parent")},
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(
                fields=["organization", "school", "is_active"],
                name="academics_p_organiz_659b3e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(fields=["email"], name="academics_p_email_120b0c_idx"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["organization", "school", "is_active"],
                name="academics_s_organiz_1a3f2f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("organization", "school", "code")},
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["organization", "school", "is_active"],
                name="academics_c_organiz_344367_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={
                ("organization", "school", "class_assigned", "subject", "academic_year")
            },
        ),
    ]
