# Generated by Django 5.2.7 on 2026-03-15 11:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_student_academic_year"),
        ("accounts", "0002_userprofile_must_change_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "low_attendance_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("75.00"),
                        help_text="Percentage below which attendance is considered low",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("allow_backdated_entry", models.BooleanField(default=True)),
                (
                    "max_backdated_days",
                    models.IntegerField(
                        default=7,
                        help_text="Maximum number of days allowed for backdated attendance entry",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "notify_parents_on_absent",
                    models.BooleanField(
                        default=False,
                        help_text="Send notification to parents when student is marked absent",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Attendance Settings",
            },
        ),
        migrations.CreateModel(
            name="ExamType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "default_max_marks",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100.00"), max_digits=5
                    ),
                ),
                (
                    "weightage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Weightage for final grade calculation",
                        max_digits=5,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GradingScale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("max_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "passing_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("exam_date", models.DateField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "class_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="academics.class",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="academics.subject",
                    ),
                ),
                (
                    "exam_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="academics.examtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-academic_year__start_date", "exam_type__display_order"],
                "unique_together": {
                    ("exam_type", "academic_year", "class_assigned", "subject")
                },
            },
        ),
        migrations.CreateModel(
            name="StudentMark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_absent", models.BooleanField(default=False)),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=5)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marks_entered",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="academics.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="academics.student",
                    ),
                ),
            ],
            options={
                "ordering": ["student__roll_number"],
            },
        ),
        migrations.CreateModel(
            name="MarkAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "old_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "new_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("old_grade", models.CharField(blank=True, max_length=5)),
                ("new_grade", models.CharField(blank=True, max_length=5)),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mark_changes",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "student_mark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="academics.studentmark",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "class_assigned",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="academics.class",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendance",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="academics.student",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_records",
                        to="academics.attendancesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "student__roll_number"],
                "indexes": [
                    models.Index(fields=["date"], name="academics_a_date_622e79_idx"),
                    models.Index(
                        fields=["status"], name="academics_a_status_f269ae_idx"
                    ),
                    models.Index(
                        fields=["class_assigned", "date"],
                        name="academics_a_class_a_cbf07d_idx",
                    ),
                    models.Index(
                        fields=["student", "date"],
                        name="academics_a_student_ec0522_idx",
                    ),
                ],
                "unique_together": {("student", "date", "session")},
            },
        ),
        migrations.CreateModel(
            name="GradeRange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("grade", models.CharField(max_length=5)),
                (
                    "min_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "max_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "grade_point",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Grade point (e.g., 4.0 for A+)",
                        max_digits=3,
                        null=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=100)),
                (
                    "grading_scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranges",
                        to="academics.gradingscale",
                    ),
                ),
            ],
            options={
                "ordering": ["-min_percentage"],
                "unique_together": {("grading_scale", "grade")},
            },
        ),
        migrations.AddIndex(
            model_name="studentmark",
            index=models.Index(
                fields=["exam", "student"], name="academics_s_exam_id_13d020_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentmark",
            index=models.Index(
                fields=["student", "exam"], name="academics_s_student_95b4a1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentmark",
            unique_together={("exam", "student")},
        ),
    ]
