# Generated by Django 6.0.3 on 2026-03-16 10:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_attendancesession_attendancesettings_examtype_and_more"),
        ("accounts", "0002_userprofile_must_change_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        help_text="Grade number (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional display name (e.g., 'Class 5')",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Order for display purposes"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["academic_year", "number"],
            },
        ),
        migrations.CreateModel(
            name="SchoolSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        default="St. Vincent Pallotti School", max_length=200
                    ),
                ),
                (
                    "school_short_name",
                    models.CharField(blank=True, default="SVPS", max_length=50),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="school/logo/"),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                (
                    "admission_number_prefix",
                    models.CharField(
                        default="SVP",
                        help_text="Prefix for admission numbers (e.g., SVP25001)",
                        max_length=10,
                    ),
                ),
                (
                    "default_section_capacity",
                    models.IntegerField(
                        default=65,
                        help_text="Default maximum students per section",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "roll_number_sort_by",
                    models.CharField(
                        default="first_name,last_name,admission_number",
                        help_text="Comma-separated fields for roll number sorting",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School Settings",
                "verbose_name_plural": "School Settings",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Section name (e.g., A, B, C)", max_length=10
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        help_text="Maximum number of students in this section",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("room_number", models.CharField(blank=True, max_length=50)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this section currently active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["grade", "name"],
            },
        ),
        migrations.AddField(
            model_name="academicyear",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Planning"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                ],
                default="planning",
                help_text="Current status of the academic year",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="is_current",
            field=models.BooleanField(
                default=False, help_text="Is this the currently active academic year?"
            ),
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="name",
            field=models.CharField(
                help_text="Academic year name (e.g., 2025-26)",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="academicyear",
            index=models.Index(fields=["status"], name="academics_a_status_e7682a_idx"),
        ),
        migrations.AddField(
            model_name="grade",
            name="academic_year",
            field=models.ForeignKey(
                help_text="Academic year this grade belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="academics.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subjects taught in this grade (same across all sections)",
                related_name="grades",
                to="academics.subject",
            ),
        ),
        migrations.AddField(
            model_name="schoolsettings",
            name="current_academic_year",
            field=models.ForeignKey(
                blank=True,
                help_text="Currently active academic year",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_year_settings",
                to="academics.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="academic_year",
            field=models.ForeignKey(
                help_text="Academic year this section belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="academics.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Class teacher assigned to this section",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_teacher_sections",
                to="accounts.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="grade",
            field=models.ForeignKey(
                help_text="Grade this section belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="academics.grade",
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["academic_year", "number"],
                name="academics_g_academi_9a0843_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["is_active"], name="academics_g_is_acti_18521e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("academic_year", "number")},
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["grade", "name"], name="academics_s_grade_i_8e9ef9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["academic_year"], name="academics_s_academi_1227cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["is_active"], name="academics_s_is_acti_91d87a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("grade", "name", "academic_year")},
        ),
    ]
