# Generated by Django 6.0.3 on 2026-03-16 10:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_grade_schoolsettings_section_academicyear_status_and_more"),
        ("accounts", "0002_userprofile_must_change_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "roll_number",
                    models.IntegerField(
                        help_text="Roll number assigned to student in this section",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "enrolled_date",
                    models.DateField(
                        help_text="Date when student was enrolled in this section"
                    ),
                ),
                (
                    "exit_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when student exited this section (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "exit_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("promoted", "Promoted"),
                            ("transferred", "Transferred"),
                            ("dropped", "Dropped"),
                            ("graduated", "Graduated"),
                        ],
                        help_text="Reason for exiting this section",
                        max_length=20,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the current active enrollment for the student?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Student Enrollment",
                "verbose_name_plural": "Student Enrollments",
                "ordering": ["-academic_year__start_date", "-enrolled_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Student photo (passport size recommended)",
                        upload_to="students/photos/%Y/%m/",
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        blank=True, help_text="Image width in pixels", null=True
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True, help_text="Image height in pixels", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        help_text="Approval status",
                        max_length=20,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the currently active photo for the student?",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this photo was approved/rejected",
                        null=True,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection (if status is rejected)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Student Photo",
                "verbose_name_plural": "Student Photos",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="class",
            options={
                "ordering": ["grade", "section"],
                "verbose_name_plural": "Classes (DEPRECATED)",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="current_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Current section the student is enrolled in",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="academics.section",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="admission_number",
            field=models.CharField(
                help_text="Permanent admission number (format: {prefix}{YY}{sequence}, e.g., SVP25001)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="current_class",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED - Use current_section instead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="academics.class",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="DEPRECATED - Use StudentPhoto model for photo management",
                null=True,
                upload_to="students/photos/",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_number",
            field=models.IntegerField(
                blank=True,
                help_text="Current roll number in current section (shortcut field)",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("graduated", "Graduated"),
                    ("transferred", "Transferred"),
                    ("dropped", "Dropped"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["current_section"], name="academics_s_current_d017e0_idx"
            ),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="academic_year",
            field=models.ForeignKey(
                help_text="Academic year for this enrollment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academics.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="section",
            field=models.ForeignKey(
                help_text="Section the student is enrolled in",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academics.section",
            ),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="student",
            field=models.ForeignKey(
                help_text="Student this enrollment belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academics.student",
            ),
        ),
        migrations.AddField(
            model_name="studentphoto",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                help_text="Academic year when this photo was uploaded",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_photos",
                to="academics.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="studentphoto",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who approved/rejected this photo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos_approved",
                to="accounts.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="studentphoto",
            name="student",
            field=models.ForeignKey(
                help_text="Student this photo belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="academics.student",
            ),
        ),
        migrations.AddField(
            model_name="studentphoto",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who uploaded this photo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos_uploaded",
                to="accounts.userprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["student", "is_current"], name="academics_s_student_24a31d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["section", "academic_year"],
                name="academics_s_section_f3837d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["academic_year", "roll_number"],
                name="academics_s_academi_8bae9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentenrollment",
            index=models.Index(
                fields=["is_current"], name="academics_s_is_curr_3cc8ed_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentenrollment",
            unique_together={("student", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="studentphoto",
            index=models.Index(
                fields=["student", "is_current"], name="academics_s_student_6ce5f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentphoto",
            index=models.Index(
                fields=["status", "academic_year"], name="academics_s_status_345ae2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentphoto",
            index=models.Index(
                fields=["is_current"], name="academics_s_is_curr_b13b85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentphoto",
            index=models.Index(
                fields=["uploaded_at"], name="academics_s_uploade_0eddae_idx"
            ),
        ),
    ]
