# Generated by Django 6.0.3 on 2026-03-16 11:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0005_studentenrollment_studentphoto_alter_class_options_and_more",
        ),
        ("accounts", "0002_userprofile_must_change_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassTeacher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True,
                        help_text="Is this the primary class teacher? (False for assistant class teachers)",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this assignment was created"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or remarks about this assignment",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        help_text="Academic year for this assignment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_teacher_assignments",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who created this assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="class_teacher_assignments_created",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="Section this class teacher is assigned to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_teacher_assignments",
                        to="academics.section",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher assigned as class teacher",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_teacher_assignments",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Class Teacher Assignment",
                "verbose_name_plural": "Class Teacher Assignments",
                "ordering": ["section", "-is_primary"],
                "indexes": [
                    models.Index(
                        fields=["section", "academic_year"],
                        name="academics_c_section_97eb74_idx",
                    ),
                    models.Index(
                        fields=["teacher", "academic_year"],
                        name="academics_c_teacher_226201_idx",
                    ),
                    models.Index(
                        fields=["academic_year", "is_primary"],
                        name="academics_c_academi_9bd64b_idx",
                    ),
                ],
                "unique_together": {("section", "academic_year", "is_primary")},
            },
        ),
        migrations.CreateModel(
            name="SubjectTeacher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "periods_per_week",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of periods per week for this subject (for timetable planning)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this assignment was created"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this assignment currently active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        help_text="Academic year for this assignment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_teacher_assignments",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who created this assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subject_teacher_assignments_created",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="Section this subject is taught to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_teacher_assignments",
                        to="academics.section",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Subject being taught",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_teacher_assignments",
                        to="academics.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Teacher assigned to teach this subject",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_teacher_assignments",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subject Teacher Assignment",
                "verbose_name_plural": "Subject Teacher Assignments",
                "ordering": ["section", "subject"],
                "indexes": [
                    models.Index(
                        fields=["section", "academic_year"],
                        name="academics_s_section_dde6ab_idx",
                    ),
                    models.Index(
                        fields=["teacher", "academic_year"],
                        name="academics_s_teacher_5eb211_idx",
                    ),
                    models.Index(
                        fields=["subject", "academic_year"],
                        name="academics_s_subject_5cc75b_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="academics_s_is_acti_319ffb_idx"
                    ),
                ],
                "unique_together": {("section", "subject", "academic_year")},
            },
        ),
    ]
