# Generated by Django 6.0.3 on 2026-03-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_classteacher_subjectteacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="roll_number",
            field=models.CharField(
                blank=True,
                help_text="Current roll number in current section (supports alphanumeric like 7A01)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="roll_number",
            field=models.CharField(
                help_text="Roll number assigned to student in this section (supports alphanumeric like 7A01)",
                max_length=20,
            ),
        ),
    ]
