# Generated by Django 6.0.3 on 2026-03-19 17:40
# Manually reordered to fix operation dependencies

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_change_roll_number_to_charfield"),
        ("accounts", "0002_userprofile_must_change_password"),
    ]

    operations = [
        # Step 1: Remove the old index that references class_assigned
        migrations.RemoveIndex(
            model_name="attendance",
            name="academics_a_class_a_cbf07d_idx",
        ),
        # Step 2: Add the new section fields first
        migrations.AddField(
            model_name="attendance",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Section for attendance tracking",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="academics.section",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Section this course is assigned to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="academics.section",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Section for exam assignment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="academics.section",
            ),
        ),
        # Step 3: Now alter unique_together constraints (section field exists)
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("section", "subject", "academic_year")},
        ),
        migrations.AlterUniqueTogether(
            name="exam",
            unique_together={("exam_type", "academic_year", "section", "subject")},
        ),
        # Step 4: Alter model options (section field exists)
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["section", "subject"]},
        ),
        # Step 5: Add new index on section
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["section", "date"], name="academics_a_section_e2fd82_idx"
            ),
        ),
        # Step 6: Remove old class_assigned fields
        migrations.RemoveField(
            model_name="attendance",
            name="class_assigned",
        ),
        migrations.RemoveField(
            model_name="course",
            name="class_assigned",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="class_assigned",
        ),
    ]
