# Generated by Django 6.0.3 on 2026-03-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0008_migrate_class_to_section"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="class",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="class",
            name="academics_c_is_acti_01dd66_idx",
        ),
        migrations.RemoveField(
            model_name="student",
            name="current_class",
        ),
        migrations.DeleteModel(
            name="Class",
        ),
    ]
