# Generated by Django 6.0.3 on 2026-03-21 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_alter_class_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={"ordering": ["academic_year", "display_order", "number"]},
        ),
        migrations.AlterField(
            model_name="grade",
            name="display_order",
            field=models.IntegerField(
                default=0,
                help_text="Order for display purposes (auto-set based on grade number if 0)",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Display name (auto-generated if not provided)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="number",
            field=models.IntegerField(
                choices=[
                    (-3, "Nursery"),
                    (-2, "Pre-KG (LKG)"),
                    (-1, "KG (UKG)"),
                    (1, "Class 1"),
                    (2, "Class 2"),
                    (3, "Class 3"),
                    (4, "Class 4"),
                    (5, "Class 5"),
                    (6, "Class 6"),
                    (7, "Class 7"),
                    (8, "Class 8"),
                    (9, "Class 9"),
                    (10, "Class 10"),
                    (11, "Class 11"),
                    (12, "Class 12"),
                ],
                help_text="Grade number: -3=Nursery, -2=Pre-KG, -1=KG, 1-12=Class 1-12",
                validators=[
                    django.core.validators.MinValueValidator(-3),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["academic_year", "display_order"],
                name="academics_g_academi_0c4e8a_idx",
            ),
        ),
    ]
