# Generated by Django 6.0.3 on 2026-03-21 18:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0010_add_pre_primary_grades"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="display_order",
            field=models.IntegerField(
                default=0,
                help_text="Order for display purposes (auto-set from grade_type if 0)",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Display name (auto-generated from grade_type if not provided)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="number",
            field=models.IntegerField(
                help_text="Grade number (synced from grade_type)",
                validators=[
                    django.core.validators.MinValueValidator(-10),
                    django.core.validators.MaxValueValidator(15),
                ],
            ),
        ),
        migrations.CreateModel(
            name="GradeType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        help_text="Unique grade number. Use negative for pre-primary (e.g., -3=Nursery, -2=Pre-KG, -1=KG)",
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(-10),
                            django.core.validators.MaxValueValidator(15),
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this grade (e.g., 'Nursery', 'Pre-KG', 'Class 5')",
                        max_length=100,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        help_text="Short name for compact displays (e.g., 'Nur', 'LKG', '5')",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pre_primary", "Pre-Primary"),
                            ("primary", "Primary"),
                            ("middle", "Middle School"),
                            ("secondary", "Secondary"),
                            ("senior_secondary", "Senior Secondary"),
                        ],
                        default="primary",
                        help_text="Category for grouping in dropdowns",
                        max_length=20,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order for display purposes (lower numbers appear first)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description for this grade type"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this grade type available for use?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Grade Type",
                "verbose_name_plural": "Grade Types",
                "ordering": ["display_order", "number"],
                "indexes": [
                    models.Index(
                        fields=["display_order", "number"],
                        name="academics_g_display_173b1a_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="academics_g_is_acti_6261f6_idx"
                    ),
                    models.Index(
                        fields=["category"], name="academics_g_categor_1ea696_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="grade",
            name="grade_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the grade type configuration",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grades",
                to="academics.gradetype",
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["grade_type"], name="academics_g_grade_t_bf4aff_idx"
            ),
        ),
    ]
