# Generated by Django 6.0.3 on 2026-03-21 19:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0011_add_grade_type_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomLayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Layout name (e.g., Room 101 Layout)", max_length=100
                    ),
                ),
                (
                    "rows",
                    models.PositiveIntegerField(help_text="Number of rows in the grid"),
                ),
                (
                    "columns",
                    models.PositiveIntegerField(
                        help_text="Number of columns (desks per row)"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Desk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "row",
                    models.PositiveIntegerField(help_text="0-indexed row position"),
                ),
                (
                    "column",
                    models.PositiveIntegerField(help_text="0-indexed column position"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Number of students this desk can seat (1-3)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="False = aisle or empty space"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional label (e.g., R1-C3)",
                        max_length=20,
                    ),
                ),
                (
                    "room_layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desks",
                        to="academics.roomlayout",
                    ),
                ),
            ],
            options={
                "ordering": ["row", "column"],
                "unique_together": {("room_layout", "row", "column")},
            },
        ),
        migrations.AddField(
            model_name="section",
            name="room_layout",
            field=models.ForeignKey(
                blank=True,
                help_text="Room layout template assigned to this section",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sections",
                to="academics.roomlayout",
            ),
        ),
        migrations.CreateModel(
            name="SeatingAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1-based position within desk (1, 2, or 3)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "desk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="academics.desk",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seating_assignments",
                        to="academics.section",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seating_assignments",
                        to="academics.student",
                    ),
                ),
            ],
            options={
                "ordering": ["desk__row", "desk__column", "position"],
                "unique_together": {
                    ("desk", "position", "section"),
                    ("section", "student"),
                },
            },
        ),
    ]
