# Generated by Django 6.0.3 on 2026-03-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0012_roomlayout_desk_section_room_layout_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schoolsettings",
            name="default_section_capacity",
        ),
        migrations.RemoveField(
            model_name="section",
            name="capacity",
        ),
    ]
