# Generated by Django 6.0.3 on 2026-03-20 09:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0008_migrate_class_to_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceLocation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Location name (e.g., 'Main Campus', 'Sports Ground')",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="Latitude coordinate",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="Longitude coordinate",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "radius_meters",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="Geofence radius in meters (50-5000)",
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary location used as default for attendance",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Attendance Location",
                "verbose_name_plural": "Attendance Locations",
                "ordering": ["-is_primary", "name"],
            },
        ),
        migrations.CreateModel(
            name="BusStop",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Stop name", max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="Unique stop code (e.g., ST01)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("landmark", models.CharField(blank=True, max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "stop_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup Only"),
                            ("drop", "Drop Only"),
                            ("both", "Pickup & Drop"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        default=50, help_text="Maximum students at this stop"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Bus Stop",
                "verbose_name_plural": "Bus Stops",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("driver", "Driver"), ("helper", "Helper/Attendant")],
                        default="driver",
                        max_length=20,
                    ),
                ),
                ("license_number", models.CharField(blank=True, max_length=50)),
                ("license_expiry", models.DateField(blank=True, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=15),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vehicle_number",
                    models.CharField(
                        help_text="Vehicle registration number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("bus", "Bus"),
                            ("mini_bus", "Mini Bus"),
                            ("van", "Van"),
                            ("tempo", "Tempo Traveller"),
                            ("other", "Other"),
                        ],
                        default="bus",
                        max_length=20,
                    ),
                ),
                ("make", models.CharField(blank=True, max_length=50)),
                ("model", models.CharField(blank=True, max_length=50)),
                (
                    "year_of_manufacture",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "seating_capacity",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("registration_expiry", models.DateField(blank=True, null=True)),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("fitness_expiry", models.DateField(blank=True, null=True)),
                ("pollution_expiry", models.DateField(blank=True, null=True)),
                ("is_gps_enabled", models.BooleanField(default=False)),
                ("gps_device_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("maintenance", "Under Maintenance"),
                            ("retired", "Retired"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "ordering": ["vehicle_number"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Route name (e.g., 'Route 1 - North')", max_length=100
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique route code", max_length=20, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "route_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup Route"),
                            ("drop", "Drop Route"),
                            ("both", "Pickup & Drop Route"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                (
                    "pickup_start_time",
                    models.TimeField(
                        blank=True, help_text="Pickup route start time", null=True
                    ),
                ),
                (
                    "drop_start_time",
                    models.TimeField(
                        blank=True, help_text="Drop route start time", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "driver"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes_as_driver",
                        to="transport.driver",
                    ),
                ),
                (
                    "helper",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "helper"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes_as_helper",
                        to="transport.driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes",
                        to="transport.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="Order of this stop in the route"
                    ),
                ),
                (
                    "pickup_time",
                    models.TimeField(
                        blank=True, help_text="Expected pickup time", null=True
                    ),
                ),
                (
                    "drop_time",
                    models.TimeField(
                        blank=True, help_text="Expected drop time", null=True
                    ),
                ),
                (
                    "distance_from_previous",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Distance from previous stop in km",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "bus_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stop_routes",
                        to="transport.busstop",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_stops",
                        to="transport.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route Stop",
                "verbose_name_plural": "Route Stops",
                "ordering": ["route", "sequence"],
                "unique_together": {("route", "bus_stop"), ("route", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "trip_type",
                    models.CharField(
                        choices=[("pickup", "Pickup"), ("drop", "Drop")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("start_odometer", models.PositiveIntegerField(blank=True, null=True)),
                ("end_odometer", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "current_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "current_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("last_location_update", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips",
                        to="transport.driver",
                    ),
                ),
                (
                    "helper",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips_as_helper",
                        to="transport.driver",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="transport.route",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips",
                        to="transport.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
                "ordering": ["-date", "trip_type"],
                "unique_together": {("route", "date", "trip_type")},
            },
        ),
        migrations.AddField(
            model_name="driver",
            name="assigned_vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_personnel",
                to="transport.vehicle",
            ),
        ),
        migrations.CreateModel(
            name="StudentStopAssignment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_assignments",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "drop_route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drop_students",
                        to="transport.route",
                    ),
                ),
                (
                    "drop_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drop_students",
                        to="transport.busstop",
                    ),
                ),
                (
                    "pickup_route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickup_students",
                        to="transport.route",
                    ),
                ),
                (
                    "pickup_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickup_students",
                        to="transport.busstop",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport_assignments",
                        to="academics.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Stop Assignment",
                "verbose_name_plural": "Student Stop Assignments",
                "unique_together": {("student", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="StudentBoardingLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "boarding_status",
                    models.CharField(
                        choices=[
                            ("boarded", "Boarded"),
                            ("alighted", "Alighted"),
                            ("absent", "Absent"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("boarding_time", models.DateTimeField(blank=True, null=True)),
                (
                    "boarding_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "boarding_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "boarding_stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="boarding_logs",
                        to="transport.routestop",
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_boardings",
                        to="transport.driver",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boarding_logs",
                        to="academics.student",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_boarding_logs",
                        to="transport.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Boarding Log",
                "verbose_name_plural": "Student Boarding Logs",
                "ordering": ["trip", "boarding_time"],
                "unique_together": {("trip", "student")},
            },
        ),
        migrations.CreateModel(
            name="TripStopLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("arrival_time", models.DateTimeField(blank=True, null=True)),
                ("departure_time", models.DateTimeField(blank=True, null=True)),
                (
                    "arrival_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "arrival_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("passengers_boarded", models.PositiveIntegerField(default=0)),
                ("passengers_alighted", models.PositiveIntegerField(default=0)),
                (
                    "route_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_logs",
                        to="transport.routestop",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_stop_logs",
                        to="transport.trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trip Stop Log",
                "verbose_name_plural": "Trip Stop Logs",
                "ordering": ["trip", "arrival_time"],
                "unique_together": {("trip", "route_stop")},
            },
        ),
    ]
