# Generated by Django 5.2.7 on 2026-03-13 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("request_submitted", "Request Submitted"),
                            ("request_approved", "Request Approved"),
                            ("request_rejected", "Request Rejected"),
                            (
                                "request_pending_approval",
                                "Request Pending Your Approval",
                            ),
                            (
                                "request_pending_clearance",
                                "Request Pending Your Clearance",
                            ),
                            ("request_completed", "Request Completed"),
                            ("request_cancelled", "Request Cancelled"),
                            ("request_bypassed", "Request Bypassed"),
                            ("clearance_granted", "Clearance Granted"),
                            ("clearance_denied", "Clearance Denied"),
                            ("clearance_pending", "Clearance Pending"),
                            ("payment_pending", "Payment Pending"),
                            ("payment_completed", "Payment Completed"),
                            ("payment_failed", "Payment Failed"),
                            ("announcement", "Announcement"),
                            ("reminder", "Reminder"),
                            ("system_alert", "System Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject line (for email/push)",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Template body with placeholders like {{user_name}}, {{request_number}}"
                    ),
                ),
                (
                    "sms_body",
                    models.CharField(
                        blank=True,
                        help_text="Short SMS version (max 160 chars)",
                        max_length=160,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["event_type", "channel"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "channel", "is_active"],
                        name="notificatio_event_t_488074_idx",
                    ),
                    models.Index(fields=["slug"], name="notificatio_slug_f965ad_idx"),
                ],
                "unique_together": {("event_type", "channel")},
            },
        ),
        migrations.CreateModel(
            name="NotificationBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_criteria",
                    models.JSONField(
                        default=dict,
                        help_text="Filter criteria for recipients (e.g., {'role': 'parent', 'class': '10A'})",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("total_recipients", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
                ("delivered_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notification_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notification batches",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_for"],
                        name="notificatio_status_80ba48_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("push_enabled", models.BooleanField(default=True)),
                (
                    "notification_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email for notifications (uses account email if blank)",
                        max_length=254,
                    ),
                ),
                (
                    "notification_phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number for SMS notifications",
                        max_length=20,
                    ),
                ),
                (
                    "email_frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("daily_digest", "Daily Digest"),
                            ("weekly_digest", "Weekly Digest"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                (
                    "event_preferences",
                    models.JSONField(
                        default=dict,
                        help_text="Fine-grained control over which events trigger which channels",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="notificatio_user_id_0299fd_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_type", models.CharField(blank=True, max_length=50)),
                (
                    "related_model",
                    models.CharField(
                        blank=True,
                        help_text="Model name (e.g., 'workflows.Request')",
                        max_length=100,
                    ),
                ),
                (
                    "related_object_id",
                    models.UUIDField(
                        blank=True, help_text="UUID of the related object", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_response",
                    models.TextField(
                        blank=True, help_text="Response from email/SMS provider"
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True,
                        help_text="Schedule notification for later",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Additional context data"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "-created_at"],
                        name="notificatio_user_id_eebdc7_idx",
                    ),
                    models.Index(
                        fields=["user", "channel", "status"],
                        name="notificatio_user_id_fd4246_idx",
                    ),
                    models.Index(
                        fields=["status", "scheduled_for"],
                        name="notificatio_status_d8d933_idx",
                    ),
                    models.Index(
                        fields=["related_model", "related_object_id"],
                        name="notificatio_related_2132fd_idx",
                    ),
                ],
            },
        ),
    ]
